In [10]:
import pandas as pd
import numpy as np

In [9]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr2 = np.random.uniform(0, 100, 50)
arr2

array([80.23492015, 51.38633399, 69.6494573 , 84.46989187, 62.51282773,
       37.77114402, 26.72451482, 84.31760346, 25.41414367, 27.13388931,
       65.96917269, 57.83591046, 54.34380263, 12.49400812, 68.88500476,
       77.26228771, 52.38160521, 66.33123076, 60.95499099, 14.56471943,
       54.56173335, 64.70862716, 15.78127351, 14.01432698, 51.72113193,
       34.81446012, 65.07591871, 98.87544462, 43.20930363, 26.26734141,
       67.11490565, 51.982547  , 48.72046673, 61.93033071, 16.1456149 ,
       57.25522587, 83.59309654, 71.18052633, 66.76238949, 80.10845339,
       82.67562861, 60.74139077, 69.20466129, 97.11958985, 48.05838243,
       94.9239582 , 86.24876899, 79.9421972 , 25.32530152, 33.88357187])

In [23]:
arr3 = np.linspace(1,10,10)
arr3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
arr4 = np.arange(1,11,1)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])